### ISSUE TITLE
Change license: GPLv3 -> 3-clause-BSD

### ISSUE THREAD

**Issue by jcarrano** [jcarrano/fixed_point_arith#1]
@nventuro, @jubeira:

GPL/LGPL es demasiado restrictiva para proyectos embebidos. En realidad, no se porqué puse esa licencia, pero si me dejan la cambio a BSD.

**Comment by nventuro** [comment]
Fine by me, either 3-clause BSD, MIT, or any other permissive license sounds great.

**Comment by jubeira** [comment]
SGTM.
Consider Apache 2.0 as an option if you want as well.
